"""class Customer adding emoji column

Revision ID: 06883ec67907
Revises: b1cabfd59249
Create Date: 2024-01-31 15:20:27.718998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06883ec67907'
down_revision = 'b1cabfd59249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('emoji')

    # ### end Alembic commands ###
