"""customers to customer

Revision ID: 205fa687a25a
Revises: e1916464f3f4
Create Date: 2024-01-31 11:52:20.098591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205fa687a25a'
down_revision = 'e1916464f3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('customers', 'customer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('customer', 'customers')
    # ### end Alembic commands ###
