"""bck to customers



Revision ID: eafc60f20f32
Revises: 205fa687a25a
Create Date: 2024-01-31 11:54:32.234284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eafc60f20f32'
down_revision = '205fa687a25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('customer', 'customers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('customers', 'customer')
    # ### end Alembic commands ###
